name: Node.js CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - run:  npm ci --cache .npm --prefer-offline
      # define cache dir & use it npm!



